# Configuration for Dependabot automatic dependency updates
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor testing dependencies only
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Only update testing dependencies, not product dependencies
    # Dependencies are controlled via the groups below
    # Group testing dependencies to reduce PR noise
    groups:
      testing-frameworks:
        patterns:
          - "xunit.*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.*"
          - "GitHubActionsTestLogger"
          - "Moq"
      microsoft-extensions-testing:
        patterns:
          - "Microsoft.Extensions.DependencyInjection"
          - "Microsoft.Extensions.Hosting"
          - "Microsoft.Extensions.Logging"
          - "Microsoft.Extensions.Logging.Console"
          - "Microsoft.Extensions.Options"
          - "Microsoft.Extensions.TimeProvider.Testing"
          - "Microsoft.Extensions.AI.OpenAI"
      opentelemetry-testing:
        patterns:
          - "OpenTelemetry*"
      serilog-testing:
        patterns:
          - "Serilog*"
      other-testing:
        patterns:
          - "Anthropic.SDK"
          - "System.Linq.AsyncEnumerable"
          - "System.Net.Http"
          - "JsonSchema.Net"
    # Ignore all product dependencies to only update testing dependencies
    ignore:
      - dependency-name: "Microsoft.Bcl.Memory"
      - dependency-name: "Microsoft.Extensions.Hosting.Abstractions"
      - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
      - dependency-name: "System.Diagnostics.DiagnosticSource"
      - dependency-name: "System.IO.Pipelines"
      - dependency-name: "System.Text.Json"
      - dependency-name: "System.Threading.Channels"
      - dependency-name: "Microsoft.AspNetCore.Authentication.JwtBearer"
      - dependency-name: "Microsoft.IdentityModel.Tokens"
      - dependency-name: "Microsoft.Extensions.AI.Abstractions"
      - dependency-name: "Microsoft.Extensions.AI"
      - dependency-name: "System.Net.ServerSentEvents"
      - dependency-name: "Microsoft.SourceLink.GitHub"
    # Limit the number of open pull requests for testing dependencies
    open-pull-requests-limit: 5
    # Add labels to dependency update PRs
    labels:
      - "dependencies"
      - "testing"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Limit the number of open pull requests for GitHub Actions to 5
    open-pull-requests-limit: 5
    # Add labels to GitHub Actions update PRs
    labels:
      - "dependencies"
      - "github-actions"